/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AppManajemenWisata;


public class detailDaftar extends javax.swing.JFrame {

//    private String kodeBooking;
//    private String nama;
//    private String alamat;
//    private String notelp;
//    private String selectedDestination;
//    private String lokasi;
//    private String tanggal;
//    private String biaya;
    
    public detailDaftar(String kodeBooking, String nama, String alamat, String noTelp, String tema, String lokasi, String tanggal, String biaya) {
        initComponents();
//        this.kodeBooking = kodeBooking;
//        this.nama = nama;
//        this.alamat = alamat;
//        this.notelp = notelp;
//        this.selectedDestination = selectedDestination;
//        this.lokasi = lokasi;
//        this.tanggal = tanggal;
//        this.biaya = biaya;
        
        kode_booking.setText(kodeBooking);
        nama_daftar.setText(nama);
        alamat_daftar.setText(alamat);
        notelp_daftar.setText(noTelp);
        tema_daftar.setText(tema);
        lokasi_daftar.setText(lokasi);
        tanggal_daftar.setText(tanggal);
        biaya_daftar.setText("IDR." + biaya);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nama_daftar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kode_booking = new javax.swing.JLabel();
        biaya_daftar = new javax.swing.JLabel();
        alamat_daftar = new javax.swing.JLabel();
        notelp_daftar = new javax.swing.JLabel();
        tema_daftar = new javax.swing.JLabel();
        lokasi_daftar = new javax.swing.JLabel();
        tanggal_daftar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Pendaftaran", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 14))); // NOI18N
        jPanel1.setLayout(null);

        nama_daftar.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        nama_daftar.setText("Nama Lengkap");
        nama_daftar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(nama_daftar);
        nama_daftar.setBounds(20, 30, 550, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenWisata/img/logo6.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(588, 30, 100, 340);

        kode_booking.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        kode_booking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kode_booking.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kode Booking", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 12))); // NOI18N
        jPanel1.add(kode_booking);
        kode_booking.setBounds(20, 290, 400, 60);

        biaya_daftar.setFont(new java.awt.Font("Poppins", 0, 36)); // NOI18N
        biaya_daftar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biaya_daftar.setText("biaya");
        biaya_daftar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Harga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 12))); // NOI18N
        jPanel1.add(biaya_daftar);
        biaya_daftar.setBounds(250, 220, 320, 70);

        alamat_daftar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        alamat_daftar.setText("Alamat");
        alamat_daftar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(alamat_daftar);
        alamat_daftar.setBounds(20, 100, 330, 50);

        notelp_daftar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        notelp_daftar.setText("No Telepon");
        notelp_daftar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(notelp_daftar);
        notelp_daftar.setBounds(360, 100, 210, 50);

        tema_daftar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tema_daftar.setText("Tema Yang Di pilih");
        tema_daftar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(tema_daftar);
        tema_daftar.setBounds(20, 160, 390, 50);

        lokasi_daftar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lokasi_daftar.setText("Lokasi");
        lokasi_daftar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lokasi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 12))); // NOI18N
        jPanel1.add(lokasi_daftar);
        lokasi_daftar.setBounds(20, 220, 220, 70);

        tanggal_daftar.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        tanggal_daftar.setText("Tanggal");
        tanggal_daftar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tanggal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 12))); // NOI18N
        jPanel1.add(tanggal_daftar);
        tanggal_daftar.setBounds(420, 160, 150, 50);

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 8)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("© Pembuatan aplikasi oleh Kelompok 4 ; Ade Amung Nugraha, Hani Riani, Haryanto Nugroho, Intan Regita Cahyani, Sifa Nurani");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 360, 550, 13);

        back.setText("KEMBALI KE MENU");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(430, 310, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new tabelBook().setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detailDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detailDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detailDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detailDaftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detailDaftar("1", "MPW001", "Tema 1", "Lokasi 1", "2024-07-01", "500000", "Kegiatan 1", "image.jpg").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat_daftar;
    private javax.swing.JButton back;
    private javax.swing.JLabel biaya_daftar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kode_booking;
    private javax.swing.JLabel lokasi_daftar;
    private javax.swing.JLabel nama_daftar;
    private javax.swing.JLabel notelp_daftar;
    private javax.swing.JLabel tanggal_daftar;
    private javax.swing.JLabel tema_daftar;
    // End of variables declaration//GEN-END:variables
    
}
