/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AppManajemenWisata;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;


/**
 *
 * @author Acer
 */
public class tabelBook extends javax.swing.JFrame {

    DefaultTableModel model;
    
    public tabelBook() {
        initComponents();
        ukuranKolom();
        dataBookingan();
        showCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new GradientPanel(51, 51, 51, 255, 153, 0);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataBooking = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bnyk_pnggna = new javax.swing.JLabel();
        bnyk_daftar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        InCari = new javax.swing.JTextField();
        TmCari = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("PERJALANAN DAN WISATA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 70, 250, 30);

        jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("DATA TABEL BOOKING CUSTOMER");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 50, 250, 30);

        dataBooking.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        dataBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataBooking.setOpaque(false);
        dataBooking.setRowHeight(25);
        dataBooking.setSelectionBackground(new java.awt.Color(255, 153, 0));
        dataBooking.setShowHorizontalLines(true);
        dataBooking.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(dataBooking);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(32, 250, 850, 320);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenWisata/img/logo3.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(730, 50, 148, 60);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        bnyk_pnggna.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        bnyk_pnggna.setForeground(new java.awt.Color(51, 51, 51));
        bnyk_pnggna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bnyk_pnggna.setText("00");
        jPanel2.add(bnyk_pnggna);

        bnyk_daftar.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        bnyk_daftar.setForeground(new java.awt.Color(51, 51, 51));
        bnyk_daftar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bnyk_daftar.setText("00");
        jPanel2.add(bnyk_daftar);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 120, 300, 80);

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("total akun");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 210, 60, 19);

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pendaftar");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(230, 210, 60, 19);

        InCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InCariActionPerformed(evt);
            }
        });
        jPanel1.add(InCari);
        InCari.setBounds(590, 160, 230, 40);

        TmCari.setText("Cari");
        TmCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TmCariActionPerformed(evt);
            }
        });
        jPanel1.add(TmCari);
        TmCari.setBounds(820, 160, 60, 40);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenWisata/img/back.png"))); // NOI18N
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(0, 0, 50, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppManajemenWisata/img/close-blck.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(860, 0, 50, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        dataForm dataForm = new dataForm();
        dataForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void InCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InCariActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Frame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Yakin pengen keluar??",
            "Aplikasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TmCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TmCariActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_TmCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        }catch(Exception e){
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabelBook().setVisible(true);
            }
        });
    }
    private void showCount(){
        int totalBaris = totalPengguna();
        int totalDaftar= totalPendaftar();
        bnyk_pnggna.setText(""+totalBaris);
        bnyk_daftar.setText(""+totalDaftar);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InCari;
    private javax.swing.JButton TmCari;
    private javax.swing.JButton back;
    private javax.swing.JLabel bnyk_daftar;
    private javax.swing.JLabel bnyk_pnggna;
    private javax.swing.JTable dataBooking;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public class GradientPanel extends JPanel {
        private Color color1;
        private Color color2;

        public GradientPanel(Color color1, Color color2) {
            this.color1 = color1;
            this.color2 = color2;
            setOpaque(false);
        }

        public GradientPanel(int r1, int g1, int b1, int r2, int g2, int b2) {
            this.color1 = new Color(r1, g1, b1);
            this.color2 = new Color(r2, g2, b2);
            setOpaque(false);
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2d = (Graphics2D) g.create();
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            int lebar = getWidth();
            int tinggi = getHeight();
            GradientPaint gp = new GradientPaint(0, 0, color1, lebar, 0, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, lebar, tinggi);

            g2d.dispose();
        }
    }
    private void dataBookingan() {
        try {
            Connection con = db.getConnection();
            ResultSet res = con.createStatement().executeQuery("SELECT tb_booking.nama_pemesan, tb_booking.alamat_pemesan, tb_booking.notelp, tb_data.tema_mpw, tb_data.lokasi_mpw, tb_data.biaya_mpw FROM tb_booking INNER JOIN tb_data ON tb_booking.kode_mpw = tb_data.kode_mpw");
            int no = 1;
            while(res.next()){
                String data [] =  {String.valueOf(no), res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)};
                model.addRow(data);
                no++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(bookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void ukuranKolom(){
        int lebarKolom [] = {20, 120, 150, 100, 150, 80, 70};
        String [] field = {"No","Nama","Alamat","No.Telp","Tema","Tujuan","Harga"};
        model = new DefaultTableModel (field, 0);
        dataBooking.setModel(model);
        dataBooking.getTableHeader().setBackground(new Color(255,151,0));
        dataBooking.getTableHeader().setForeground(new Color(255,255,255));
        dataBooking.getTableHeader().setFont(new Font("Poppins",Font.PLAIN, 12));
        for (int i = 0; i < lebarKolom.length; i++) {
            dataBooking.getColumnModel().getColumn(i).setPreferredWidth(lebarKolom[i]);
        }
    }
    private int totalPengguna(){
        int totalRows = 0;
        try (Connection con = db.getConnection(); Statement stmt = con.createStatement()){
            String pilih1 = "SELECT COUNT(*) FROM tb_pengguna WHERE role = 'user'";
            ResultSet rs1 = stmt.executeQuery(pilih1);
            if (rs1.next()) {
                totalRows = rs1.getInt(1);
                System.out.println("Total Rows: " + totalRows);
            }
        } catch (SQLException ex) {
            Logger.getLogger(dataForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return totalRows;
    }
    private int totalPendaftar(){
        int totalRows = 0;
        try (Connection con = db.getConnection(); Statement stmt = con.createStatement()){
            String pilih2 = "SELECT COUNT(*) FROM tb_booking";
            ResultSet rs2 = stmt.executeQuery(pilih2);
            if ( rs2.next()) {
                totalRows = rs2.getInt(1);
                System.out.println("Total Rows: " + totalRows);
            }
        } catch (SQLException ex) {
            Logger.getLogger(dataForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return totalRows;
    }
    private void cari() {
        int row = dataBooking.getRowCount();
        for (int i = 0; i < row; i++) {
            model.removeRow(0);
        }
        String cari= "%" + InCari.getText() + "%";
        try {
            int no = 1;
            Connection con = db.getConnection();
            String query = "SELECT tb_booking.nama_pemesan, tb_booking.alamat_pemesan, tb_booking.notelp, tb_data.tema_mpw, tb_data.lokasi_mpw, tb_data.biaya_mpw " +
                       "FROM tb_booking INNER JOIN tb_data ON tb_booking.kode_mpw = tb_data.kode_mpw " +
                        "WHERE tb_booking.nama_pemesan LIKE '%" + cari + "%' OR tb_booking.alamat_pemesan LIKE '%" + cari + "%' OR tb_booking.notelp LIKE '%" + cari + "%' OR tb_data.tema_mpw LIKE '%" + cari + "%' OR tb_data.lokasi_mpw LIKE '%" + cari + "%'";
            PreparedStatement ps = con.prepareStatement(query);
            

            ResultSet r = ps.executeQuery(query);
            while (r.next()) {
                String data [] =  {String.valueOf(no), r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6)};
                model.addRow(data);
                no++;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
}
